# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.auth_proto import auth_pb2 as protos_dot_auth__proto_dot_auth__pb2


class AuthenticationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/authentication.Authentication/Login',
                request_serializer=protos_dot_auth__proto_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=protos_dot_auth__proto_dot_auth__pb2.LoginResponse.FromString,
                )
        self.Register = channel.unary_unary(
                '/authentication.Authentication/Register',
                request_serializer=protos_dot_auth__proto_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=protos_dot_auth__proto_dot_auth__pb2.RegisterResponse.FromString,
                )
        self.RequestPasswordReset = channel.unary_unary(
                '/authentication.Authentication/RequestPasswordReset',
                request_serializer=protos_dot_auth__proto_dot_auth__pb2.RequestPasswordResetRequest.SerializeToString,
                response_deserializer=protos_dot_auth__proto_dot_auth__pb2.RequestPasswordResetResponse.FromString,
                )
        self.ResetPassword = channel.unary_unary(
                '/authentication.Authentication/ResetPassword',
                request_serializer=protos_dot_auth__proto_dot_auth__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=protos_dot_auth__proto_dot_auth__pb2.ResetPasswordResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/authentication.Authentication/GetUser',
                request_serializer=protos_dot_auth__proto_dot_auth__pb2.GetUserRequest.SerializeToString,
                response_deserializer=protos_dot_auth__proto_dot_auth__pb2.GetUserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/authentication.Authentication/UpdateUser',
                request_serializer=protos_dot_auth__proto_dot_auth__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=protos_dot_auth__proto_dot_auth__pb2.UpdateUserResponse.FromString,
                )
        self.UpdateProfilePicture = channel.unary_unary(
                '/authentication.Authentication/UpdateProfilePicture',
                request_serializer=protos_dot_auth__proto_dot_auth__pb2.UpdateProfilePictureRequest.SerializeToString,
                response_deserializer=protos_dot_auth__proto_dot_auth__pb2.UpdateProfilePictureResponse.FromString,
                )


class AuthenticationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPasswordReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfilePicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=protos_dot_auth__proto_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=protos_dot_auth__proto_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=protos_dot_auth__proto_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=protos_dot_auth__proto_dot_auth__pb2.RegisterResponse.SerializeToString,
            ),
            'RequestPasswordReset': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPasswordReset,
                    request_deserializer=protos_dot_auth__proto_dot_auth__pb2.RequestPasswordResetRequest.FromString,
                    response_serializer=protos_dot_auth__proto_dot_auth__pb2.RequestPasswordResetResponse.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=protos_dot_auth__proto_dot_auth__pb2.ResetPasswordRequest.FromString,
                    response_serializer=protos_dot_auth__proto_dot_auth__pb2.ResetPasswordResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=protos_dot_auth__proto_dot_auth__pb2.GetUserRequest.FromString,
                    response_serializer=protos_dot_auth__proto_dot_auth__pb2.GetUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=protos_dot_auth__proto_dot_auth__pb2.UpdateUserRequest.FromString,
                    response_serializer=protos_dot_auth__proto_dot_auth__pb2.UpdateUserResponse.SerializeToString,
            ),
            'UpdateProfilePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfilePicture,
                    request_deserializer=protos_dot_auth__proto_dot_auth__pb2.UpdateProfilePictureRequest.FromString,
                    response_serializer=protos_dot_auth__proto_dot_auth__pb2.UpdateProfilePictureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authentication.Authentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authentication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/Login',
            protos_dot_auth__proto_dot_auth__pb2.LoginRequest.SerializeToString,
            protos_dot_auth__proto_dot_auth__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/Register',
            protos_dot_auth__proto_dot_auth__pb2.RegisterRequest.SerializeToString,
            protos_dot_auth__proto_dot_auth__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPasswordReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/RequestPasswordReset',
            protos_dot_auth__proto_dot_auth__pb2.RequestPasswordResetRequest.SerializeToString,
            protos_dot_auth__proto_dot_auth__pb2.RequestPasswordResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/ResetPassword',
            protos_dot_auth__proto_dot_auth__pb2.ResetPasswordRequest.SerializeToString,
            protos_dot_auth__proto_dot_auth__pb2.ResetPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/GetUser',
            protos_dot_auth__proto_dot_auth__pb2.GetUserRequest.SerializeToString,
            protos_dot_auth__proto_dot_auth__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/UpdateUser',
            protos_dot_auth__proto_dot_auth__pb2.UpdateUserRequest.SerializeToString,
            protos_dot_auth__proto_dot_auth__pb2.UpdateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProfilePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/UpdateProfilePicture',
            protos_dot_auth__proto_dot_auth__pb2.UpdateProfilePictureRequest.SerializeToString,
            protos_dot_auth__proto_dot_auth__pb2.UpdateProfilePictureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
