# Generated by Django 5.0 on 2023-12-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldata',
            name='WalletSecurityStamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
