# Generated by Django 5.0 on 2023-12-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userpersonaldata_walletsecuritystamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonaldata',
            old_name='WalletSecurityStamp',
            new_name='wallet_security_stamp',
        ),
    ]
