# Generated by Django 5.0 on 2023-12-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_walletsecuritystamp_userpersonaldata_wallet_security_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonaldata',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userpersonaldata',
            name='profile_picture_drive_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
